### ISSUE TITLE
Can't start Keepnote 6.0 on Ubuntu Jaunty 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#100]
```
What steps will reproduce the problem?
1. sudo dpkg -i  keepnote_0.6-1_all.deb
2. (at command line) keepnote &

Expected Keepnote to run.

Received :

Traceback (most recent call last):
  File "/usr/local/bin/keepnote", line 247, in <module>
    main(sys.argv)
  File "/usr/local/bin/keepnote", line 205, in main
    main_proc, cmd_exec = get_command_executor(False, execute_command)
TypeError: get_command_executor() takes exactly 1 argument (2 given)

Previous version (5.3) was running happily.

```

Original issue reported on code.google.com by `templewo...@gmail.com` on 21 Aug 2009 at 4:30

**Comment by GoogleCodeExporter** [comment]
```
Can you tell me what this says:

   python -c 'import keepnote; print keepnote'

Thanks.  This might be an install problem.
Matt

```

Original comment by `matt.rasmus@gmail.com` on 21 Aug 2009 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
all I get is :

<module 'keepnote' from 
'/usr/lib/python2.6/dist-packages/keepnote/__init__.pyc'>

thanks.
```

Original comment by `templewo...@gmail.com` on 22 Aug 2009 at 5:50

**Comment by GoogleCodeExporter** [comment]
```
ahh...
Version 0.6 appears to be installed in /usr/local/ (notice the
"/usr/local/bin/keepnote" in your previous error message) but the old libraries 
are
in /usr/ (notice "/usr/lib/python2.6/dist-packages/keepnote/__init__.pyc").  So
delete the directory 
   /usr/lib/python2.6/dist-packages/keepnote

to uninstall the old library.  You can also just rename the directory to 
something
else (e.g. "/usr/lib/python2.6/dist-packages/keepnote.old") in order to test 
whether
my idea works.  After this KeepNote should be able to find the correct library
(probably in "/usr/local/lib/python2.6/dist-packages/keepnote").

Let me know if this works.

Matt
```

Original comment by `matt.rasmus@gmail.com` on 22 Aug 2009 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
Thanks.

Sorry, but this turned out to be my bad. I had installed the previous 
5.3.tar.gz as 
a local package, and put a Keepnote link to the binary under /usr/local/bin.

After installing 6.1 from the .deb package it seems that I was trying to start 
the
5.3 binary with the new 6.1 files now installed.

Deleted the link in /usr/local/bin and 0.6 is now running smoothly.

Apologies for the input of a red herring.
```

Original comment by `templewo...@gmail.com` on 23 Aug 2009 at 2:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 23 Aug 2009 at 3:43
- Changed state: **Fixed**
