### ISSUE TITLE
0.6 does not start on (my) windows XP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#107]
```
What steps will reproduce the problem?
1. run the installer
2. run keepnote

What is the expected output? What do you see instead?

nothing happens, in a cmd window prompt returns nearly immediatly.
version 0.5.3 was OK

See the log below:

KeepNote 0.6: Tue Aug 25 11:25:04 2009
Traceback (most recent call last):
  File "keepnote", line 259, in <module>
  File "keepnote", line 247, in main
  File "keepnote\gui\__init__.pyc", line 173, in __init__
  File "keepnote\__init__.pyc", line 802, in __init__
  File "keepnote\__init__.pyc", line 544, in __init__
  File "keepnote\__init__.pyc", line 302, in get_user_documents
  File "keepnote\mswin\__init__.pyc", line 11, in get_my_documents
NameError: global name 'shell' is not defined

```

Original issue reported on code.google.com by `Pierre.H...@alcatel-lucent.fr` on 26 Aug 2009 at 3:40

**Comment by GoogleCodeExporter** [comment]
```
When did you download the testing version?  If it was a few days ago, I may have
already added a fix for this bug.  (I just recently received a bug report for 
this
issue I think I have fixed it).

Try re-downloading the testing version again (I made an update in-place) and 
reinstall.  
http://rasm.ods.org/keepnote/download-test/

Let me know if this fixes the issue.  Thanks for your feedback.

Matt

```

Original comment by `matt.rasmus@gmail.com` on 26 Aug 2009 at 3:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 1 Sep 2009 at 4:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi there, 

I just had the same problem and have just downloaded the last version 
available. The 
previous ones too and it doesn´t seem to work also. 

I installed and it just doesn´t load. I copy paste the logs:

I really would like some help for this since I am trying to use it for work 
purposes.

Thank you very much!

Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: invalid 
data
Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: invalid 
data
Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: invalid 
data

```

Original comment by `victor.g...@gmail.com` on 28 Apr 2010 at 2:36
