### ISSUE TITLE
Exporting notebook fail if some page title have accent marks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#108]
```
What steps will reproduce the problem?
1. Create a new notebook
2. Create a page named with accent marks (by exemple : déjà vu)
3. Export the notebook as HTML

What is the expected output? What do you see instead?
Expected : the notebook should be exported
See instead : An error dialog box "Unkown error"


What version of the product are you using? On what operating system?
0.6

Please provide any additional information below.


```

Original issue reported on code.google.com by `pascal.c...@gmail.com` on 27 Aug 2009 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
I use Linux Kubuntu 9.04 (KDE)

env|egrep '(LANG|LC)' =>
LANG=fr_FR.UTF-8
LANGUAGE=


Here is the log file content :

==============================================
KeepNote 0.6: Thu Aug 27 17:54:05 2009
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 500, in
on_edit_title
    node.rename(new_text)            
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 752, in
rename
    self._notebook._index.add_node(self)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309, in
add_node
    node.get_attr("icon_load"), nodeid))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.
/usr/lib/python2.6/urllib.py:1220: UnicodeWarning: Unicode equal comparison 
failed to
convert both arguments to Unicode - interpreting them as being unequal
  res = map(safe_map.__getitem__, s)

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/tasklib.py", line 139, in _new_thread
    self._func(self)
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
151, in <lambda>
    export_notebook(notebook, filename, task))
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
506, in export_notebook
    export_node(notebook, notebook.get_path(), filename, True)
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
466, in export_node
    write_index(notebook, node, arcname)
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
385, in write_index
    walk(node)
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
382, in walk
    walk(child)
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
374, in walk
    % (nodeid2html_link(notebook, rootpath, nodeid),
  File
"/usr/lib/python2.6/dist-packages/keepnote/extensions/export_html/__init__.py", 
line
217, in nodeid2html_link
    return urllib.quote(newpath)
  File "/usr/lib/python2.6/urllib.py", line 1220, in quote
    res = map(safe_map.__getitem__, s)
KeyError: u'\xe9'

```

Original comment by `pascal.c...@gmail.com` on 27 Aug 2009 at 3:58

**Comment by GoogleCodeExporter** [comment]
```
I found the bug for this error (did not encode unicode urls properly).  The fix 
will
appear soon on the testing website.

```

Original comment by `matt.rasmus@gmail.com` on 27 Aug 2009 at 4:02
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Can you please try the updated testing version (27-Aug-2009 12:00):
http://rasm.ods.org/keepnote/download-test/

I believe this should now be fixed.  Thanks for your feedback.
```

Original comment by `matt.rasmus@gmail.com` on 27 Aug 2009 at 7:14

**Comment by GoogleCodeExporter** [comment]
```
Matt,

It does work with a small notebook (created for test), but not with the big one 
I
really use for my notes. I'll do some tests further (resulting export is 
partial, so
I can look where it fails) and give you a another feedback.
```

Original comment by `pascal.c...@gmail.com` on 27 Aug 2009 at 9:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks for this testing.  It is very useful for me.  Let me know what the error 
log
says or if you find any other clues.
```

Original comment by `matt.rasmus@gmail.com` on 27 Aug 2009 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
I've found where the error come from !

In my notebook, while writing some pages, I've created links for "future pages" 
to be
written later (see our discussion about this feature at
http://groups.google.com/group/keepnote/browse_thread/thread/4fb852550305c9c3?hl
=en).
To do that, I've tried PageTitle and nbk://pageTitle as links to see if one of 
them
create a page on double click. This second kind of "false link" makes export 
fail
with "unkown error" issue.

See the attached notebook to reproduce the bug (exporting in HTML fails).
```

Original comment by `pascal.c...@gmail.com` on 28 Aug 2009 at 8:08

Attachments:
- [Issue108.tar.gz](https://storage.googleapis.com/google-code-attachments/keepnote/issue-108/comment-6/Issue108.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
Great, thanks!  This is a good test case to add.  I think I will have a fixed 
posted
later today.
```

Original comment by `matt.rasmus@gmail.com` on 28 Aug 2009 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I should have a fix for this now.  Please try the testing version 
"30-Aug-2009
10:50".
http://rasm.ods.org/keepnote/download-test/

```

Original comment by `matt.rasmus@gmail.com` on 30 Aug 2009 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
Resolved ! Exporting notebook with accents marked page titles works fine now.

Thanks

PS : By error, i've posted this comment on issue #110 first (I've deleted it 
now)
```

Original comment by `pascal.c...@gmail.com` on 30 Aug 2009 at 6:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 30 Aug 2009 at 7:00
- Changed state: **Fixed**
