### ISSUE TITLE
Moving page or folder fails if it's titled with accent marks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#110]
```
What steps will reproduce the problem?
1. Create a new notebook
2. Add a page named "Déjà vu"
3. Add a folder "Some folder" somewhere
4. Add a child page in "Some folder"
5. Drag and drop "Déjà vu" page inside "Some folder" (as a child page)

What is the expected output? What do you see instead?
Expected : the page should be moved in the folder
See instead : Error dialog box with the message "Do not have permission for
move".


What version of the product are you using? On what operating system?
Keepnote 0.6 / Linux KDE 9.04

Please provide any additional information below.


```

Original issue reported on code.google.com by `pascal.c...@gmail.com` on 27 Aug 2009 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
I cannot reproduce this error on my system.  Can you tell me what your LANG
environment variable is set to.  What is the output of:
  env | egrep '(LANG|LC)'

What does the KeepNote error log say?  "Help > Show Error Log"

Thanks for your feedback.
```

Original comment by `matt.rasmus@gmail.com` on 27 Aug 2009 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
**************** The command line output is *********
    LANG=fr_FR.UTF-8
    LANGUAGE=


**************** What the KeepNote log says ****************

1- After starting KeepNote :

    ==============================================
    KeepNote 0.6: Thu Aug 27 17:36:01 2009

2- After a page is renamed "Déjà vu" :

    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 500,
in on_edit_title
    node.rename(new_text)            
      File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line
752, in rename
    self._notebook._index.add_node(self)
      File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309,
in add_node
    node.get_attr("icon_load"), nodeid))
    sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.

3- After I've tried to move the page inside a folder (the drag and drop 
operation
seems to be ignored):

    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 782,
in _on_drag_data_received
    selection_data, info, eventtime)
      File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 848,
in _on_drag_node_received
    source_node.move(new_parent, new_path[-1])
      File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line
639, in move
    self._notebook._index.add_node(self)
      File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309,
in add_node
    node.get_attr("icon_load"), nodeid))
    sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.

4- After I've tried a second time to move the page (error dialog box pop up 
now):

    NoteBookError: OSError(2, 'Aucun fichier ou dossier de ce type')
    Do not have permission for move


I hope it can help.
Pascal
```

Original comment by `pascal.c...@gmail.com` on 27 Aug 2009 at 3:50

Attachments:
- [error-log.txt](https://storage.googleapis.com/google-code-attachments/keepnote/issue-110/comment-2/error-log.txt)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for this bug report.
Can you please try the updated testing version (27-Aug-2009 12:00):
http://rasm.ods.org/keepnote/download-test/

I believe this should now be fixed.
```

Original comment by `matt.rasmus@gmail.com` on 27 Aug 2009 at 7:15

**Comment by GoogleCodeExporter** [comment]
```
Thanks Matt. 

I'm sorry, it still happens. 

I've tried with the new deb version (305 962 bytes) and new tar.gz version (349 
280
bytes) after a clean uninstall (using "apt-get remove keepnote" and removing
~/.config/takenote folder).

But, I've discovered something around it. The first time I try to move the page 
"Déjà
vu" inside a folder, it seems nothing happens. But, if I close the notebook and 
open
it again, the page has actually moved. I can move it until it's renamed (then 
the bug
will reappear).

Unfortunately, I can't access error log now, with this updated version (Error 
"could
not open error log"). 
```

Original comment by `pascal.c...@gmail.com` on 27 Aug 2009 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
I've notice on my two PCs that the last nightly build doesn't produce any log 
file in
~/.config/takenote directory.
```

Original comment by `pascal.c...@gmail.com` on 28 Aug 2009 at 8:10

**Comment by GoogleCodeExporter** [comment]
```
The error log should be in
~/.local/share/takenote/error-log.txt

Also if you run from the command line you should be able to see any errors.  
The main
issue here is that you are running python2.6 (which I have not tested against
before).  python2.6's sqlite library is stricter about unicode usage and the 
indexing
phase of the notebook manipulation is having an exception.  

I thought I addressed this issue (and may be I did), but I need to see the error
messages to know for sure.  Also, I am installing python2.6 and the necessary 
libs to
see if I can recreate your errors.


```

Original comment by `matt.rasmus@gmail.com` on 28 Aug 2009 at 1:44
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Here is the log :

### 1- Launching Keepnote
==============================================
KeepNote 0.6: Fri Aug 28 15:56:44 2009

### 2- Renaming a page "Déjà vu"
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 500, in
on_edit_title
    node.rename(new_text)            
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 752, in
rename
    self._notebook._index.add_node(self)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309, in
add_node
    node.get_attr("icon_load"), nodeid))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.

### 3- Trying to move the "Déjà vu" page (seems ignored):
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 782, in
_on_drag_data_received
    selection_data, info, eventtime)
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 848, in
_on_drag_node_received
    source_node.move(new_parent, new_path[-1])
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 639, in
move
    self._notebook._index.add_node(self)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309, in
add_node
    node.get_attr("icon_load"), nodeid))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.

The log file is attached below.
```

Original comment by `pascal.c...@gmail.com` on 28 Aug 2009 at 2:03

Attachments:
- [error-log.txt](https://storage.googleapis.com/google-code-attachments/keepnote/issue-110/comment-7/error-log.txt)

**Comment by GoogleCodeExporter** [comment]
```
Previously, I was unable to open log file using "Help/View Error Log" because 
I'd
reset the whole configuration and then, there were no more helper application 
for
text files... :-)
```

Original comment by `pascal.c...@gmail.com` on 28 Aug 2009 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
I could not reproduce this, even when I installed python2.6.  I did however, 
try to
track down all unicode errors I could find.  Please see if the latest testing 
version
for works for you "30-Aug-2009 10:50".
http://rasm.ods.org/keepnote/download-test/

```

Original comment by `matt.rasmus@gmail.com` on 30 Aug 2009 at 5:52

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Unlikely, it's still there.

I think the real bug is on page renaming. The others come because of this first 
one.

Also, the test case could be reduced to theses simples steps :
1- Create a notebook (or open an existing one)
2- Create a new page
3- Rename this page "Déjà vu" (or anything else with accent marks, I suppose)

Result in log :
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/basetreeview.py", line 500, in
on_edit_title
    node.rename(new_text)            
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 753, in
rename
    self._notebook._index.add_node(self)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/index.py", line 309, in
add_node
    (nodeid, title, u"", nodeid))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a
text_factory that can interpret 8-bit bytestrings (like text_factory = str). It 
is
highly recommended that you instead just switch your application to Unicode 
strings.

```

Original comment by `pascal.c...@gmail.com` on 30 Aug 2009 at 7:01

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I made many fixes for unicode throughout KeepNote.  Please try the new test
release "01-Sep-2009 09:00".  Thanks for your patience. 
http://rasm.ods.org/keepnote/download-test/
```

Original comment by `matt.rasmus@gmail.com` on 1 Sep 2009 at 4:02

**Comment by GoogleCodeExporter** [comment]
```
Congratulation, this bug is fixed. Renaming and moving works fine, and nothing 
is
reported in log.

Thanks
```

Original comment by `pascal.c...@gmail.com` on 1 Sep 2009 at 4:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 1 Sep 2009 at 5:06
- Changed state: **Fixed**
