### ISSUE TITLE
can not start keepnote 0.6 using mandriva

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#129]
```
What steps will reproduce the problem?
I tried two things:
from the tar.gz, after the extraction of the archive, I tried to start with
this command line: 
keepnote-0.6/bin/keepnote. 

I got this error:

keepnote-0.6/keepnote/rc/locale
Traceback (most recent call last):
  File "keepnote", line 259, in <module>
    main(sys.argv)
  File "keepnote", line 236, in main
    lambda app, argv: gobject.timeout_add(
  File "~/keepnote-0.6/keepnote/commands.py", line 272, in get_command_executor
    main_proc = cmd_exec.setup(execfunc)
  File "~/keepnote-0.6/keepnote/commands.py", line 214, in setup
    raise Exception("Could not open socket")
Exception: Could not open socket

(this was working with version 0.5.3)

Then I tried with the rpm, "keepnote-0.6-1.noarch.rpm", and get this error
message:

keepnote-0.6-1.noarch (car python(abi)[== 2.5] est non satisfait)

I'm using mandriva 2009 spring, the python version is Python 2.6.1

It seems that mandriva is not providing python(abi) package. 


Thank you to take care of my problem, 

During my phD, I was using knowit as a lab book, but it's not working any
more with kde4, So your keepnote seems to be exactly the soft I was looking
for thank you very much for it, I hope I will manage to install it.

```

Original issue reported on code.google.com by `roger.bu...@gmail.com` on 18 Sep 2009 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
do you have any restrictions about opening sockets on localhost?  Can you do 
this
without errors?

   netcat -l -p 8888 localhost

where 8888 is some unprivileged port number.  KeepNote expects to be able to 
open a
port anywhere between 4000-10000.  This is that KeepNote can run as one 
instance.
```

Original comment by `matt.rasmus@gmail.com` on 18 Sep 2009 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
If you do not want this feature you can try running keepnote as

  keepnote --newproc 

This will not open a socket.  The socket feature will allow you in later 
version to
control keepnote from another process.  Right now you can use

  keepnote --cmd focus

to raise all currently open keepnote windows.  This is especially handy if you 
use
your desktop to set keyboard shortcuts to command-line programs.


```

Original comment by `matt.rasmus@gmail.com` on 18 Sep 2009 at 4:52

**Comment by GoogleCodeExporter** [comment]
```
Thank you for you answer, I have tried your propositions:
for the first command 
netcat -l -p 8888 localhost
I have got the answer 
localhost: forward host lookup failed: Unknown host : Connection timed out

The command keepnote --newproc effectively start the program

the commande --cmd focus give the following errors:

Traceback (most recent call last):
  File "bin/keepnote", line 259, in <module>
    main(sys.argv)
  File "bin/keepnote", line 236, in main
    lambda app, argv: gobject.timeout_add(
  File "/home/bruno/rpm/SOURCES/keepnote-0.6/keepnote/commands.py", line 272, in
get_command_executor
    main_proc = cmd_exec.setup(execfunc)
  File "/home/bruno/rpm/SOURCES/keepnote-0.6/keepnote/commands.py", line 214, in setup
    raise Exception("Could not open socket")
Exception: Could not open socket



```

Original comment by `roger.bu...@gmail.com` on 22 Sep 2009 at 10:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 25 Oct 2009 at 4:20
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Keepnote 0.6.1 has been included in Mandriva (I'm the maintainer).
I've included it in cooker, and it's in backports for 2010.0.
```

Original comment by `ofau...@gmail.com` on 25 Dec 2009 at 9:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Jan 2010 at 4:34
- Changed state: **Done**
