### ISSUE TITLE
Tree view hangs if Ctrl-N pressed while renaming outline

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#143]
```
What steps will reproduce the problem?

1.  Renaming outline

2.  Press Ctr-N  (instead of Enter)

What is the expected output? 

Either nothing or create a new page.

What do you see instead?

Created a new page but tree view hanged up.

What version of the product are you using? On what operating system?

0.6, XP sp2

Please provide any additional information below.

Has to close and reopen the notebook.

Thank you

John

```

Original issue reported on code.google.com by `magic00...@gmail.com` on 14 Oct 2009 at 8:35
- Merged into: #93

**Comment by GoogleCodeExporter** [comment]
```
Sorry, forgot to attach the traceback


KeepNote 0.6: Wed Oct 14 13:21:50 2009
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 668, in _on_drag_begin
  File "keepnote\gui\basetreeview.pyc", line 223, in <lambda>
TypeError: iter must be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 708, in _on_drag_motion
  File "keepnote\gui\basetreeview.pyc", line 601, in get_drag_node
TypeError: iter must be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 708, in _on_drag_motion
  File "keepnote\gui\basetreeview.pyc", line 601, in get_drag_node
TypeError: iter must be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 776, in _on_drag_data_get
TypeError: iter should be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 668, in _on_drag_begin
  File "keepnote\gui\basetreeview.pyc", line 223, in <lambda>
TypeError: iter must be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 708, in _on_drag_motion
  File "keepnote\gui\basetreeview.pyc", line 601, in get_drag_node
TypeError: iter must be a GtkTreeIter
Traceback (most recent call last):
  File "keepnote\gui\basetreeview.pyc", line 776, in _on_drag_data_get
TypeError: iter should be a GtkTreeIter


```

Original comment by `magic00...@gmail.com` on 14 Oct 2009 at 8:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 18 Oct 2009 at 5:14
- Changed state: **Duplicate**
