### ISSUE TITLE
Bug: xmlerror on first start after installation on windows-xp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#146]
```
What steps will reproduce the problem?
1. I did install it on 2 xp and one vista but a third xp does not want to 
start.
2. I had Python v221 on it, without ever using it. So I uninstalled Python 
and Keepnote and re-install Keepnote without any more success
3. Keepnote ask to go on the internet (zonalarm firewall asking me if it 
is ok, answer is yes) and i see the icon in the notification then it 
disappears and nothing else happens !
What is the expected output? What do you see instead?
Error at starting

What version of the product are you using? On what operating system?
KeepNote v060 and winXP SP3

Please provide any additional information below.

See error.log (takenote)

```

Original issue reported on code.google.com by `jmati...@gmail.com` on 27 Oct 2009 at 3:48

Attachments:
- [error-log.txt](https://storage.googleapis.com/google-code-attachments/keepnote/issue-146/comment-0/error-log.txt)

**Comment by GoogleCodeExporter** [comment]
```
Here is the error file (just in case ...)
==============================================
KeepNote 0.6: Mon Oct 26 23:00:44 2009
Traceback (most recent call last):
  File "keepnote", line 259, in <module>
  File "keepnote", line 247, in main
  File "keepnote\gui\__init__.pyc", line 173, in __init__
  File "keepnote\__init__.pyc", line 844, in __init__
  File "keepnote\__init__.pyc", line 612, in read
  File "keepnote\__init__.pyc", line 681, in write
  File "keepnote\xmlobject.pyc", line 376, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 171, in write
XmlError: bad text (id,None): <type 'NoneType'>
==============================================
KeepNote 0.6: Mon Oct 26 23:02:15 2009
Traceback (most recent call last):
  File "keepnote", line 259, in <module>
  File "keepnote", line 249, in main
  File "keepnote", line 214, in execute_command
  File "keepnote\gui\__init__.pyc", line 185, in new_window
  File "keepnote\gui\main_window.pyc", line 157, in __init__
  File "keepnote\gui\main_window.pyc", line 315, in set_view_mode
  File "keepnote\__init__.pyc", line 681, in write
  File "keepnote\xmlobject.pyc", line 376, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 172, in write
  File "codecs.pyc", line 303, in write
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 32-34: invalid 
data
==============================================
KeepNote 0.6: Mon Oct 26 23:20:14 2009
Traceback (most recent call last):
  File "keepnote", line 259, in <module>
  File "keepnote", line 249, in main
  File "keepnote", line 214, in execute_command
  File "keepnote\gui\__init__.pyc", line 185, in new_window
  File "keepnote\gui\main_window.pyc", line 157, in __init__
  File "keepnote\gui\main_window.pyc", line 315, in set_view_mode
  File "keepnote\__init__.pyc", line 681, in write
  File "keepnote\xmlobject.pyc", line 376, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 172, in write
  File "codecs.pyc", line 303, in write
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 32-34: invalid 
data

```

Original comment by `jmati...@gmail.com` on 27 Oct 2009 at 3:52

**Comment by GoogleCodeExporter** [comment]
```
Can you try the latest version of KeepNote? (0.6.1 in testing phase):
http://rasm.ods.org/keepnote/download-test/

Thanks.
```

Original comment by `matt.rasmus@gmail.com` on 11 Nov 2009 at 6:17

**Comment by GoogleCodeExporter** [comment]
```
Hi,
I did install the version 0.6.1 (.exe) and still nothing seems to happen at 
startup 
time. Here is the log :
KeepNote 0.6.1: Sat Nov 21 06:49:14 2009
Traceback (most recent call last):
  File "keepnote", line 287, in <module>
  File "keepnote", line 275, in main
  File "keepnote\gui\__init__.pyc", line 301, in __init__
  File "keepnote\__init__.pyc", line 819, in __init__
  File "keepnote\__init__.pyc", line 613, in read
  File "keepnote\listening.pyc", line 60, in notify
  File "keepnote\__init__.pyc", line 557, in _on_changed
  File "keepnote\__init__.pyc", line 633, in write
  File "keepnote\xmlobject.pyc", line 376, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 165, in write
  File "keepnote\xmlobject.pyc", line 172, in write
  File "codecs.pyc", line 303, in write
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 32-34: invalid 
data
Thank you
```

Original comment by `jmati...@gmail.com` on 21 Nov 2009 at 12:16

**Comment by GoogleCodeExporter** [comment]
```
Look at the file 'notebook.nbk' inside your notebook folder.  Open it with 
'WordPad'
(not notepad).  Are there any unusual characters (non-ascii) in the file?  Try
deleting them and saving the file.  Now try to launch KeepNote.  My guess is 
somehow
this file got a character in it that does not have the proper encoding (utf8).


```

Original comment by `matt.rasmus@gmail.com` on 21 Nov 2009 at 8:36

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I did check with wordpad and pspad (in hexa) and everything is looking fine. I 
used 
french accentuated words in the html. All the .xml is looking fine too, as far 
as I 
can tell. 
The .log is still the same as the last time.
I try to rename the .nbk and even the directory and it's allways the same 
result !

Here is the notebook.nbk file's content :
<?xml version="1.0" encoding="UTF-8"?>
<notebook>
<version>3</version>
<default_font>sans 10</default_font>
<index_dir></index_dir>
<selected_treeview_nodes>753b42bb-b113-4d62-831b-
1bf4d00f80a3</selected_treeview_nodes>
<selected_listview_nodes>753b42bb-b113-4d62-831b-
1bf4d00f80a3</selected_listview_nodes>
<quick_pick_icons>
<icon>folder.png</icon>
<icon>folder-red.png</icon>
<icon>folder-orange.png</icon>
<icon>folder-yellow.png</icon>
<icon>folder-green.png</icon>
<icon>folder-blue.png</icon>
<icon>folder-violet.png</icon>
<icon>folder-grey.png</icon>
<icon>note.png</icon>
<icon>note-red.png</icon>
<icon>note-orange.png</icon>
<icon>note-yellow.png</icon>
<icon>note-green.png</icon>
<icon>note-blue.png</icon>
<icon>note-violet.png</icon>
<icon>note-grey.png</icon>
<icon>star.png</icon>
<icon>heart.png</icon>
<icon>check.png</icon>
<icon>x.png</icon>
<icon>important.png</icon>
<icon>question.png</icon>
<icon>web.png</icon>
<icon>note-unknown.png</icon>
</quick_pick_icons>
</notebook> 

Here is the takenote.xml_xxx.tmp file's content :
<?xml version="1.0" encoding="UTF-8"?>
<takenote>
<id>9717d31c-857e-4465-9601-3418cda0f99d</id>
<language></language>
<default_notebook></default_notebook>
<use_last_notebook>1</use_last_notebook>
<view_mode>vertical</view_mode>
<window_size>800,600</window_size>
<window_maximized>1</window_maximized>
<vsash_pos>200</vsash_pos>
<hsash_pos>200</hsash_pos>
<treeview_lines>1</treeview_lines>
<listview_rules>1</listview_rules>
<use_stock_icons>0</use_stock_icons>
<use_minitoolbar>0</use_minitoolbar>
<image_size_snap>1</image_size_snap>
<image_size_snap_amount>50</image_size_snap_amount>
<use_systray>1</use_systray>
<skip_taskbar>0</skip_taskbar>
<spell_check>1</spell_check>
<autosave>1</autosave>
<autosave_time>10000</autosave_time>
<new_notebook_path>

Here is the takenote.xml file's content :
<?xml version="1.0" encoding="UTF-8"?>
<takenote>
</takenote>

If there is something else that I could check or send to you, just ask.

Thank you

```

Original comment by `jmati...@gmail.com` on 26 Nov 2009 at 10:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Jun 2010 at 6:01
- Changed state: **Done**
- Added labels: **encoding**
