### ISSUE TITLE
Can´t open

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#156]
```
I can't open keepnote!

Please help

Traceback (most recent call last):
  File "keepnote", line 259, in <module>
  File "keepnote", line 236, in main
  File "keepnote\commands.pyc", line 272, in get_command_executor
  File "keepnote\commands.pyc", line 214, in setup
Exception: Could not open socket
```

Original issue reported on code.google.com by `laureano...@gmail.com` on 21 Nov 2009 at 5:42

**Comment by GoogleCodeExporter** [comment]
```

I disabled my hosts file and now I can open Keepnote!

Can anybody tell me what entry in Hosts file is doing the problem?  
```

Original comment by `laureano...@gmail.com` on 21 Nov 2009 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
You must be blocking localhost connections.  KeepNote uses these (just like 
firefox)
to communicate between keepnote processes.  To disable this you can run 
keepnote as:

  keepnote --newproc

from the commandline.
```

Original comment by `matt.rasmus@gmail.com` on 21 Nov 2009 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks
```

Original comment by `laureano...@gmail.com` on 23 Nov 2009 at 8:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 24 Nov 2009 at 2:20
- Changed state: **Done**
