### ISSUE TITLE
empty takenote.xml - can't open keepnote

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#157]
```
What steps will reproduce the problem?
Basically I just can't open keepnote? 


What is the expected output? What do you see instead?
I expected Keepnote to open - in stead I get this error:
==============================================
KeepNote 0.6: Sun Nov 22 10:59:34 2009
Traceback (most recent call last):
  File "/usr/bin/keepnote", line 259, in <module>
    main(sys.argv)
  File "/usr/bin/keepnote", line 247, in main
    app = keepnote.gui.KeepNote(basedir)
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/__init__.py", line
173, in __init__
    keepnote.KeepNote.__init__(self, basedir)
  File "/usr/lib/python2.6/dist-packages/keepnote/__init__.py", line 844,
in __init__
    self.pref.read()
  File "/usr/lib/python2.6/dist-packages/keepnote/__init__.py", line 623,
in read
    get_user_pref_file(self._pref_dir))
  File "/usr/lib/python2.6/dist-packages/keepnote/xmlobject.py", line 355,
in read
    raise XmlError("Error reading file '%s': %s" % (filename, str(e)))
XmlError: Error reading file '/home/andreas/.config/takenote/takenote.xml':
no element found: line 1, column 0

takenote.xml is empty - but I have not touced it?

What version of the product are you using? On what operating system?
0.6 - linux

Please provide any additional information below.


```

Original issue reported on code.google.com by `achristo...@gmail.com` on 22 Nov 2009 at 10:03

**Comment by GoogleCodeExporter** [comment]
```
Reinstall after purge does not help???
```

Original comment by `achristo...@gmail.com` on 22 Nov 2009 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
delete takenote.xml and start keepnote (it will then be repopulated).  I don't 
know
how it became blank.  Did you stop keepnote while it was writing to disk?  Let 
me
know if this works.


```

Original comment by `matt.rasmus@gmail.com` on 22 Nov 2009 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
Hi Matt, Thanks for your reply

Deleting takenote.xml had no effect. Remove the whole directory let me start up
keepnote. But when I tried to open a notebook folder, I get this error:

NoteBookError: XmlError(u"Error reading file
'/home/andreas/Documents/proj/Noter/proj/notebook.nbk': no element found: line 
1,
column 0",)
Notebook preference data is corrupt

The file notebook.nbk exist - but is empty.

```

Original comment by `achristo...@gmail.com` on 22 Nov 2009 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
Ps. sometimes I cant resume after suspend (old hardware) - so I guess it is 
possible
that keepnote have been interrupted. 
```

Original comment by `achristo...@gmail.com` on 22 Nov 2009 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
Ok. so we solved the first problem (configuration file problems), now we need 
to fix
your notebook.  KeepNote is very conservative: if something is out of place it
refuses to proceed.  This is so that it does accidentally overwrite 
information.  For
this next issue replace the contents of the file
/home/andreas/Documents/proj/Noter/proj/notebook.nbk

With 
<?xml version="1.0" encoding="UTF-8"?>
<notebook>
</notebook>


Now trying opening the notebook in KeepNote.
```

Original comment by `matt.rasmus@gmail.com` on 22 Nov 2009 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
It's good to be consevative. But even with the new notebook.nbk the notebook 
will not
open.

This is what I get: 
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/main_window.py", line 627, in
open_notebook
    notebook = self.app.open_notebook(filename, self)
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/__init__.py", line 220, in
open_notebook
    notebook.load(filename)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 1282,
in load
    self.read_meta_data()
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 933, in
read_meta_data
    self._notebook.notebook_attrs)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 1715,
in read
    raise NoteBookError(_("Cannot read meta data"), e)
NoteBookError: ExpatError('no element found: line 1, column 0',)
Cannot read meta data

```

Original comment by `achristo...@gmail.com` on 22 Nov 2009 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
What does the node.xml file inside notebook say?  If it is blank you can 
replace its
contents with

<?xml version="1.0" encoding="UTF-8"?>
<node>
</node>

To check your whole notebook you can do:
find YOUR_NOTEBOOK_FOLDER -name node.xml | xargs --replace=X file X | grep empty

to see if any of the node.xml files are empty

Let me know if this works.

```

Original comment by `matt.rasmus@gmail.com` on 22 Nov 2009 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
Thank you! It now works. 
I think KeepNote is a definite keeper. Basically a OneNote replacement was all 
I ever
missed leaving windows. Now it finally looks like I have found a leaner, faster 
and
simpler (in a good way) replacement. I love Keepnote.

(and as a added bonus: I have never used xargs before... thank for showing me).

I guess the issue can be closed now?
```

Original comment by `achristo...@gmail.com` on 22 Nov 2009 at 10:41

**Comment by GoogleCodeExporter** [comment]
```
great.  good to hear everything works now.  
```

Original comment by `matt.rasmus@gmail.com` on 22 Nov 2009 at 10:49
- Changed state: **Done**
