### ISSUE TITLE
Not opening on linux.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#177]
```
What steps will reproduce the problem?
1. click on icon to open Keepnote

What is the expected output? What do you see instead?
I expect Keepnote to open, it does not


What version of the product are you using? On what operating system?
Version 6.1 and 6.0 on eeebuntu 3.0
eeebuntu 3.0=Ubuntu 9.04

Please provide any additional information below.

On Eeebuntu I uninstalled version 6.0 and installed version 6.1.  Keepnote
would not open at all, no errors.  It appears in System monitor for a
second then vanishes.  I removed 6.1 and reinstalled 6.0 but it still won't
open.  

I have restored a back up of my notes.  

```

Original issue reported on code.google.com by `Antonia....@gmail.com` on 5 Jan 2010 at 6:42

**Comment by GoogleCodeExporter** [comment]
```
What errors do you get if you run in it in a terminal?  Or what errors show up 
in
~/.config/takenote/error-log.txt
```

Original comment by `matt.rasmus@gmail.com` on 5 Jan 2010 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
Thank you for the prompt reply.

There is no error log and when I run it in terminal I get this:

Traceback (most recent call last):
  File "/usr/bin/keepnote", line 259, in <module>
    main(sys.argv)
  File "/usr/bin/keepnote", line 247, in main
    app = keepnote.gui.KeepNote(basedir)
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/__init__.py", line 173, in __init__
    keepnote.KeepNote.__init__(self, basedir)
  File "/usr/lib/python2.6/dist-packages/keepnote/__init__.py", line 844, in __init__
    self.pref.read()
  File "/usr/lib/python2.6/dist-packages/keepnote/__init__.py", line 623, in read
    get_user_pref_file(self._pref_dir))
  File "/usr/lib/python2.6/dist-packages/keepnote/xmlobject.py", line 353, in read
    parser.ParseFile(infile)
  File "/usr/lib/python2.6/dist-packages/keepnote/xmlobject.py", line 321, in
__end_element
    raise XmlError("Malformed XML")
XmlError: Malformed XML

Antonia
```

Original comment by `Antonia....@gmail.com` on 5 Jan 2010 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
It looks like your preference file got corrupted.  Try moving/deleting
"~/.config/takenote" out of the way and KeepNote will recreate it.

You can also try and fix the existing file.  Open 
~/.config/takenote/takenote.xml and
see if it is truncated.  It should end with "</takenote>".

Matt
```

Original comment by `matt.rasmus@gmail.com` on 5 Jan 2010 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
Thank you, deleting the takenote folder fixed it.

This is an excellent program.  Thanks  for your help and for writing this 
program.

Antonia
```

Original comment by `Antonia....@gmail.com` on 5 Jan 2010 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
Great!  Glad to hear that worked.
```

Original comment by `matt.rasmus@gmail.com` on 5 Jan 2010 at 8:44
- Changed state: **Done**
