### ISSUE TITLE
Cannot enable spell checking on Mac OSX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#187]
```
I can't get the option to enable spell checking to itself be enabled.  I 
remember having a similar issue in Linux (which I ran previously) but 
this time I can't seem to fix it.  The error that I get is:

File 
"/Users/post/Installations/keepnote-0.6.1/keepnote/gui/richtext/__init__.py", 
line 1289, in enable_spell_check
    self._spell_checker = gtkspell.Spell(self)
GError: enchant error for language: en
logout

I have installed gnome-python-extras, enchant and gtkspell2 from MacPorts, is 
there anything else I need to do?


```

Original issue reported on code.google.com by `michaelj...@googlemail.com` on 19 Jan 2010 at 6:30

**Comment by GoogleCodeExporter** [comment]
```
Further to this issue, having installed the packages listed I now can't launch
keepnote at all.  I get the following in the terminal:

Xlib:  extension "RANDR" missing on display "/tmp/launch-cgbifn/:0".
==============================================
KeepNote 0.6.1: Mon Jan 25 08:38:35 2010
enabling extension 'export_html'
enabling extension 'editor_insert_date'
enabling extension 'keepnote'
enabling extension 'backup_tar'
Traceback (most recent call last):
  File "/Users/post/Installations/keepnote-0.6.1/bin/keepnote", line 298, in <module>
    main(sys.argv)
  File "/Users/post/Installations/keepnote-0.6.1/bin/keepnote", line 288, in main
    execute_command(app, argv)
  File "/Users/post/Installations/keepnote-0.6.1/bin/keepnote", line 236, in
execute_command
    win = app.new_window()
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/__init__.py", line 326,
in new_window
    window = keepnote.gui.main_window.KeepNoteWindow(self)
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/main_window.py", line
111, in __init__
    self.init_layout()
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/main_window.py", line
143, in init_layout
    self.viewer = self.new_viewer()
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/main_window.py", line
213, in new_viewer
    viewer = ThreePaneViewer(self._app, self)
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/three_pane_viewer.py",
line 118, in __init__
    self.editor = KeepNoteEditor(self._app)
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/editor.py", line 100,
in __init__
    self._app.get_richtext_tag_table()))    # textview
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/richtext/__init__.py",
line 334, in __init__
    self.enable_spell_check(True)
  File "/Users/post/Installations/keepnote-0.6.1/keepnote/gui/richtext/__init__.py",
line 1289, in enable_spell_check
    self._spell_checker = gtkspell.Spell(self)
GError: enchant error for language: en
logout

[Process completed]



Please help, I can't take any notes and am rapidly building up a library of text
documents that I'll later have to copy back into my notebook!

```

Original comment by `michaelj...@googlemail.com` on 25 Jan 2010 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
You might need aspell and aspell-en

On my Debian machine the packages are installed as
sudo apt-get install aspell aspell-en

perhaps ports has similar names.  If this works for let me know and I will add 
it to
the documentation.  Sorry for the inconvenience.
```

Original comment by `matt.rasmus@gmail.com` on 25 Jan 2010 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
I had aspell but was missing aspell-en.  Installing that worked, KeepNote is now
working perfectly and spell-checks!  For the record, MacPorts has aspell but 
calls
aspell-en "aspell-dict-en".

Thanks for your help!

```

Original comment by `michaelj...@googlemail.com` on 26 Jan 2010 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
Great!  Thanks for telling me the name of the package.  I will include it in the
documentation.
```

Original comment by `matt.rasmus@gmail.com` on 26 Jan 2010 at 12:49
- Changed state: **Done**
