### ISSUE TITLE
Date displays in incorrect symbols for non-latin languages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#201]
```
Date in "created" and "modified" columns of ListView displays with
incorrect characters for non-latin languages (if Date/Time format settings
in Regional Settings of Windows uses language with non-latin symbols).
Maybe there is a problem with encoding (in get_str_timestamp function or
elsewhere) or with font (which is unlikely because text in other columns
displays correctly).

Example is shown for English and Russian dates on screenshots.

I am using KeepNote v0.6.1 on MS Windows Vista Home Basic Russian SP1.
```

Original issue reported on code.google.com by `tema...@gmail.com` on 2 Feb 2010 at 8:59

Attachments:
- [Cyrillic_problem_rus.png](https://storage.googleapis.com/google-code-attachments/keepnote/issue-201/comment-0/Cyrillic_problem_rus.png)
- [Cyrillic_problem_eng.png](https://storage.googleapis.com/google-code-attachments/keepnote/issue-201/comment-0/Cyrillic_problem_eng.png)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for this bug report.  Can you try the latest testing version 
keepnote-0.6.2?
http://rasm.ods.org/keepnote/download-test/

Thanks.
```

Original comment by `matt.rasmus@gmail.com` on 2 Feb 2010 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
Thank you. I have tried keepnote-0.6.2.exe . Unfortunately, problem still 
remains.
```

Original comment by `tema...@gmail.com` on 2 Feb 2010 at 2:47

**Comment by GoogleCodeExporter** [comment]
```
In keepnote 0.6.2 can you open up the python prompt "Tools > Python Prompt"
and type in the upper text box:

import sys, time
print sys.getdefaultencoding()
e = sys.getdefaultencoding()
print time.strftime("%B %a")
print time.strftime(u"%B %a")
print time.strftime("%B %a").decode(e)
print time.strftime(u"%B %a").decode(e)

Then press ctrl+enter to evaluate it.  Tell me what appears in the output box 
(lower
textbox).  Thanks.
```

Original comment by `matt.rasmus@gmail.com` on 2 Feb 2010 at 3:27

**Comment by GoogleCodeExporter** [comment]
```
Thank you. For this code output is following:
================================================================================
====
utf-8



Traceback (most recent call last):
  File "C:\Program Files\KeepNote\extensions\python_prompt\dialog_python.py", line
234, in execute
  File "<string>", line 6, in <module>
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid 
data
================================================================================
====

The problem is in two last lines of code while first two print's (those ones 
without
.decode(e) ) output is blank because it is not in unicode I suppose. I have 
managed
to solve problem using following code:

import sys, time, locale
LOCALE_ENCODING = locale.getdefaultlocale()[1]
print LOCALE_ENCODING
print unicode(time.strftime("%B %a"), LOCALE_ENCODING, 'strict')
print unicode(time.strftime(u"%B %a"), LOCALE_ENCODING, 'strict')


In this case output for this code is (as expected):
================================================================================
====
cp1251
Лютий Ср
Лютий Ср
================================================================================
====
```

Original comment by `tema...@gmail.com` on 3 Feb 2010 at 7:39

**Comment by GoogleCodeExporter** [comment]
```
This helps me a lot.  I will update you when I think I have a fix in place in 
the
testing version.
```

Original comment by `matt.rasmus@gmail.com` on 3 Feb 2010 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I have uploaded what I think will fix this issue.  Can you try the latest
testing version?
http://rasm.ods.org/keepnote/download-test/

Thanks.
```

Original comment by `matt.rasmus@gmail.com` on 3 Feb 2010 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
I have downloaded last keepnote-0.6.2.exe and everything works well now.
Thank you for support!
```

Original comment by `tema...@gmail.com` on 4 Feb 2010 at 5:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 4 Feb 2010 at 6:27
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Jun 2010 at 5:50
- Changed state: **Done**
- Added labels: **encoding**
