### ISSUE TITLE
Error running keepnote on Mac OS - no module named pygtk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#266]
```
Hello!  I've previously posted Mac OS related issues (which were all fixed very 
quickly and well).  
I've had reason to reinstall OS X (Snow Leopard) and am now trying to get 
Keepnote working 
again.  I must have done something last time around that I haven't this time 
because I'm getting 
the following error when trying to run it:

-------------------------------------------------------

Last login: Tue Apr 20 14:29:32 on ttys000
/Users/michaelpost/Applications/keepnote-0.6.2/bin/keepnote ; exit;
Michael-Posts-MacBook-Pro:~ michaelpost$ 
/Users/michaelpost/Applications/keepnote-
0.6.2/bin/keepnote ; exit;
Traceback (most recent call last):
  File "/Users/michaelpost/Applications/keepnote-0.6.2/bin/keepnote", line 352, in <module>
    main(sys.argv)
  File "/Users/michaelpost/Applications/keepnote-0.6.2/bin/keepnote", line 345, in main
    start_gui(argv, options, args, cmd_exec)
  File "/Users/michaelpost/Applications/keepnote-0.6.2/bin/keepnote", line 212, in start_gui
    import keepnote.gui
  File "/Users/michaelpost/Applications/keepnote-0.6.2/keepnote/gui/__init__.py", line 39, in 
<module>
    import pygtk
ImportError: No module named pygtk
logout

[Process completed]

---------------------------------------------------

I've installed everything python/gtk related that I can find in MacPorts but 
still keep getting this 
error.  Google doesn't yield any results, any ideas?
```

Original issue reported on code.google.com by `michaelj...@googlemail.com` on 20 Apr 2010 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
I think it's called 'py26-gtk' in mac ports, but I can't verify as my computer 
is
pretty broken right now.
```

Original comment by `clouserw` on 10 May 2010 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
Make sure you run with the python from mac ports.  You need to do something 
like:

python2.5 /Users/michaelpost/Applications/keepnote-0.6.2/bin/keepnote

Let me know if this works.
```

Original comment by `matt.rasmus@gmail.com` on 15 Jun 2010 at 5:04
- Changed state: **Started**
- Added labels: **install**

**Comment by GoogleCodeExporter** [comment]
```
Same issue here...
[18:33:30][aejara@aejara-mb:~]$ /Applications/Test/keepnote-0.6.4/bin/keepnote
Traceback (most recent call last):
  File "/Applications/Test/keepnote-0.6.4/bin/keepnote", line 360, in <module>
    main(sys.argv)
  File "/Applications/Test/keepnote-0.6.4/bin/keepnote", line 353, in main
    start_gui(argv, options, args, cmd_exec)
  File "/Applications/Test/keepnote-0.6.4/bin/keepnote", line 215, in start_gui
    import keepnote.gui
  File "/Applications/Test/keepnote-0.6.4/keepnote/gui/__init__.py", line 39, in <module>
    import pygtk
ImportError: No module named pygtk


When I try tu run it with python, I get...
[18:33:41][aejara@aejara-mb:~]$ python2.5 
/Applications/Test/keepnote-0.6.4/bin/keepnote
Traceback (most recent call last):
  File "/Applications/Test/keepnote-0.6.4/bin/keepnote", line 83, in <module>
    import keepnote
  File "/Applications/Test/keepnote-0.6.4/keepnote/__init__.py", line 47, in <module>
    from keepnote.notebook import \
  File "/Applications/Test/keepnote-0.6.4/keepnote/notebook/__init__.py", line 50, in <module>
    from keepnote import trans
  File "/Applications/Test/keepnote-0.6.4/keepnote/trans.py", line 28, in <module>
    import ctypes
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes


I ddn't saved the log form all dependencies isntall using ports, but I didn't 
see any strange (except it took hours to install all dependencies).

```

Original comment by `aej...@gmail.com` on 15 Aug 2010 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
I like keepnote because I have a PC and work and a Mac at home.  I installed 
via the mac ports instructions. Here are my results which are virtually 
identical to the ones above.


alan-rakess-macbook:bin alanrakes$ python2.5 ./keepnote
Traceback (most recent call last):
  File "./keepnote", line 83, in <module>
    import keepnote
  File "/Users/alanrakes/Documents/keepnote-0.6.4/keepnote/__init__.py", line 47, in <module>
    from keepnote.notebook import \
  File "/Users/alanrakes/Documents/keepnote-0.6.4/keepnote/notebook/__init__.py", line 50, in <module>
    from keepnote import trans
  File "/Users/alanrakes/Documents/keepnote-0.6.4/keepnote/trans.py", line 28, in <module>
    import ctypes
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes


I know there have been ctypes errors a few years ago with Darwin, but I thought 
those had been solved.


```

Original comment by `aara...@bellsouth.net` on 1 Oct 2010 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
The issue appears to be related to the version of Python being called by 
keepnote.  

The error appears from the following statement:

from _ctypes import Union, Structure, Array

When called from Python2.5 as called for in the program you get this:

alan-rakess-macbook:~ alanrakes$ python2.5
Python 2.5.5 (r255:77872, Oct  1 2010, 13:48:20) 
[GCC 4.2.1 (Apple Inc. build 5664)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from _ctypes import Union, Structure, Array
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _ctypes
>>> 

However, the default Python installed with Snow Leopard is Python 2.6.1

alan-rakess-macbook:~ alanrakes$ Python --version
Python 2.6.1

When I call the same command from it I get no error message, but I don't have 
access to pygtk so I can't use it as currently configured.


Type "help", "copyright", "credits" or "license" for more information.
>>> from _ctypes import Union, Structure, Array
>>> 
(note no error message about module _ctypes)


```

Original comment by `aara...@bellsouth.net` on 2 Oct 2010 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
Workaround solution found for Snow Leopard.

Since the default Python in Snow Leopard is already 2.6.1, and it does not have 
the _ctypes problem, I found a precompiled disk image of pygtk that works with 
snow leopard and downloaded it from this page
http://kedeligdata.blogspot.com/2009/09/native-mac-pygtk-for-snow-leopard.html

After following the instructions to add it to my PYTHONPATH environment I was 
able to launch keepnote successfully and read in a backup I had previously 
saved from another computer.


```

Original comment by `aara...@bellsouth.net` on 2 Oct 2010 at 9:12

**Comment by GoogleCodeExporter** [comment]
```
This seems to be easy to follow solution: 
http://stackoverflow.com/questions/1380281/set-snow-leopard-to-use-python-2-5-ra
ther-than-2-6
```

Original comment by `Alar.Mae...@gmail.com` on 6 Oct 2010 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
I was never able to get some crashes overcome with the method I used above.  I 
was also never able to get the _ctypes problem resolved when working with the 
MacPorts Python installation.

I basically punted using those approaches and went back to using the fink 
project at fink.sourceforge.net.  From there I issued one command

    fink install pygtk2-gtk-py26
This installed pygtk with all the associated dependencies including Python2.6.

Now it launches fine with no crashes at all with the command
    python2.6 keepnote

Now I have working copies of keepnote for both my Mac notebook at home and my 
PC at work.
```

Original comment by `aara...@bellsouth.net` on 14 Oct 2010 at 12:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 23 Feb 2011 at 3:54
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
I have had several issues before I could get keepnote 0.7.8 running with MacOS 
Mountain Lion

1.) It could not deal with the locale. Error looked like this:

(process:13737): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
...
...
raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

I fixed this by creating a little script that you can find attached at the end.

2.) I had the above described problem 
import pygtk
ImportError: No module named pygtk

This was fixed as described by using the macports version of Python aka 
python2.7

3.) I had a display problem because I forgot to reinstall the MacOS x11 server 
that can be found here:
http://xquartz.macosforge.org/landing/

The error I got was something like:

GtkWarning: could not open display

After I have installed everything needed and used this script ( I created a 
symbolic link to it for convenience) it FINALLY worked.

Script: (you might have to adjust it to your locale though)

#!/bin/bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
#/opt/local/bin/python2.7 /usr/share/keepnote-0.7.5/bin/keepnote
python2.7 /usr/share/keepnote-0.7.8/bin/keepnote 

```

Original comment by `christia...@googlemail.com` on 24 Aug 2012 at 5:10
