### ISSUE TITLE
Do not Start in XP Profesional after installation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#269]
```
What steps will reproduce the problem?
1. Download the installer for windows.  (OK)
2. Install by executing .exe (OK)
3. Clic on icon to start program. (FAILED)

What is the expected output? What do you see instead?
Looking at the task manager while clicking on the start icon, you see the 
task starts for a second and disappear. 

What version of the product are you using? On what operating system?
Tried with all the 6 versions and the 0.5.3 also.

Please provide any additional information below.
The Log report says: 
Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: 
invalid data
Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: 
invalid data
Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 37-39: 
invalid data


```

Original issue reported on code.google.com by `victor.g...@gmail.com` on 29 Apr 2010 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
Do you happen to run python on your windows computer?  If so, I would really 
like to
know the result of the following code:

import os, sys
FS_ENCODING = sys.getfilesystemencoding()
print FS_ENCODING
print repr(unicode(os.getenv(u"APPDATA"), FS_ENCODING))



```

Original comment by `matt.rasmus@gmail.com` on 1 May 2010 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
 Hi matt,

I don´t think so, since the computer where I tried to install and run the 
keepnote 
software is the computer at work.

As a matter of information anyway, and maybe beeing a little stupid, could you 
tell 
me what should I do with this code? Copy-Paste it somewhere?

Many thanks!
```

Original comment by `victor.g...@gmail.com` on 1 May 2010 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem

Following is my result:

>>> import os, sys
>>> FS_ENCODING = sys.getfilesystemencoding()
>>> print FS_ENCODING
mbcs
>>> print repr(unicode(os.getenv(u"APPDATA"),FS_ENCODING))
u'D:\\Documents and Settings\\Administrator\\Application Data'
>>> 
```

Original comment by `stream19...@gmail.com` on 3 Jun 2010 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
I have fix this problem!

I set my document folder to an un-ASCII name folder.

After I changed my document folder to "My Doc",the Problem is done!

BTW, I am from China.
```

Original comment by `stream19...@gmail.com` on 3 Jun 2010 at 3:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Jun 2010 at 5:02
- Changed state: **Done**
