### ISSUE TITLE
Freeze on startup when default notebook can't be found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#315]
```
What steps will reproduce the problem?
1. I think I have a default notebook on a usb drive.
2. Open Keepnote without having drive mounted.
3.

What is the expected output? What do you see instead?
I expected to get a response that it couldn't find the notebook. Instead it 
froze.  In the terminal I got the following:

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/main_window.py", line 637, in func
    task=task)
  File "/usr/lib/python2.6/dist-packages/keepnote/__init__.py", line 890, in get_notebook
    notebook = self.open_notebook(filename, window, task=task)
  File "/usr/lib/python2.6/dist-packages/keepnote/gui/__init__.py", line 404, in open_notebook
    version = notebooklib.get_notebook_version(filename)
  File "/usr/lib/python2.6/dist-packages/keepnote/notebook/__init__.py", line 262, in get_notebook_version
    raise NoteBookError(_("Cannot read notebook preferences"), e)
keepnote.notebook.NoteBookError: IOError(2, 'No such file or directory')
Cannot read notebook preferences



What version of the product are you using? On what operating system?
0.6.3 on Linux Mint 9

Please provide any additional information below.


```

Original issue reported on code.google.com by `scott.wa...@gmail.com` on 22 Jul 2010 at 7:29
- Merged into: #309

**Comment by GoogleCodeExporter** [comment]
```
I was mistaken. I had "open last notebook", not default.  I was able to use 
Keepnote by putting in the USB drive.
```

Original comment by `scott.wa...@gmail.com` on 22 Jul 2010 at 7:33

**Comment by GoogleCodeExporter** [comment]
```
Can you please test my new testing version of KeepNote 0.6.4 and see if it 
fixes this issue.  If it does I will release 0.6.4 so that others don't run 
into this annoying bug ;).  Thanks!
```

Original comment by `matt.rasmus@gmail.com` on 22 Jul 2010 at 8:20
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
The testing versions of KeepNote are here:
http://rasm.ods.org/keepnote/download-test/


```

Original comment by `matt.rasmus@gmail.com` on 22 Jul 2010 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Problem solved it now returns a not found warning popup. Thanks. 
```

Original comment by `roelfrenkema` on 23 Jul 2010 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
Great!  Good to hear.
```

Original comment by `matt.rasmus@gmail.com` on 23 Jul 2010 at 1:28
