### ISSUE TITLE
Loss of format when pasting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#326]
```
What steps will reproduce the problem?
1. Copying text via Edit -> Paste, right click or ctrl-v into KeepNote

What is the expected output? What do you see instead?
Italics, bold, etc
Plain text

What version of the product are you using? On what operating system?
0.6.4
Windows XP

I tried pasting from:
Word 2003
PolyEdit Lite
Wordpad
Google Chrome browser

Please provide any additional information below.
Drag and drop test from the one I care the most about:
Word 2003: clipboard.targets = ('UTF8_STRING', 'DataObject', 'Object 
Descriptor', 'Rich Text Format', 'HTML Format', 'Embed Source', 'Native', 
'OwnerLink', 'Link Source', 'Link Source Descriptor', 'ObjectLink', 
'Hyperlink', 'Ole Private Data')

(Total PS)
I really love your program, it's exactly what I need but pleeeaaase add a 
windows version spell check. Then I wouldn't have to copy/paste back and forth 
from Word. =/ (And 3rd part spell check programs seem to have clipboard issues 
as well.)
```

Original issue reported on code.google.com by `LadyRav...@gmail.com` on 2 Sep 2010 at 12:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 10 Sep 2010 at 8:52
- Added labels: **copy-paste**

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 10 Sep 2010 at 8:52
- Added labels: **copypaste**
- Removed labels: **copy-paste**

**Comment by GoogleCodeExporter** [comment]
```
Issue 375 has been merged into this issue.
```

Original comment by `matt.rasmus@gmail.com` on 9 Dec 2010 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
Getting close to a full year now and I still have this issue. I've tried it on 
four different computers (Two XP, Vista, W7). I seriously love the setup but 
it's useless to me if I can't spellcheck OR copy it over to something that can 
spellcheck and paste back. 
```

Original comment by `LadyRav...@gmail.com` on 15 Aug 2011 at 7:06

**Comment by GoogleCodeExporter** [comment]
```
I've add more support for maintaining formatting when copying and pasting in 
the testing version of keepnote 0.7.5.  Let me know if this improves your copy 
and paste behavior. Thanks.
http://keepnote.org/#download-test
```

Original comment by `matt.rasmus@gmail.com` on 31 Aug 2011 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Sadly, still a no-go. Copy/paste from Word, Wordpad, Chrome, etc still paste 
only plain text.
```

Original comment by `LadyRav...@gmail.com` on 31 Aug 2011 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I have just re-uploaded another attempt in-place.  If you have time can 
you re-download testing version 0.7.5 and let me know if formatting improves.  
Thanks!
```

Original comment by `matt.rasmus@gmail.com` on 31 Aug 2011 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Hm, not sure what happened there but regular paste no longer seems to work at 
all; however, selecting "Paste as plain text" does work. 

I checked the error log and found this error repeatedly:

TypeError: 'NoneType' object is unsubscriptable
Traceback (most recent call last):
  File "C:\Program Files\KeepNote\extensions\python_prompt\__init__.pyc", line 856, in _do_paste_html

  File "C:\Program Files\KeepNote\extensions\python_prompt\__init__.pyc", line 153, in parse_utf

```

Original comment by `LadyRav...@gmail.com` on 1 Sep 2011 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
Ok.  I found the issue.  I am now able to copy and paste from microsoft word on 
my own computer.  If you have time, can you try the latest testing version, 
again? Thanks!
http://keepnote.org/#download-test
```

Original comment by `matt.rasmus@gmail.com` on 1 Sep 2011 at 4:11
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Works like a charm! Thanks for all the hard work.  =)
```

Original comment by `LadyRav...@gmail.com` on 1 Sep 2011 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
Great! Thank so much for your patience and testing.
```

Original comment by `matt.rasmus@gmail.com` on 1 Sep 2011 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
I accidentally added an additional copy/paste bug for copy and paste within 
keepnote. Please re-download/install keepnote 0.7.5 to fix this.
http://keepnote.org/#download-test
```

Original comment by `matt.rasmus@gmail.com` on 2 Sep 2011 at 1:29

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Sep 2011 at 2:31
- Changed state: **Done**
