### ISSUE TITLE
slow file opening with 0.6.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#331]
```
What steps will reproduce the problem?
1.opening existing older notebook
2.
3.

What is the expected output? What do you see instead?
Using keepnote since 0.6.0 my rather small notebook (about 20 pages text ony) 
opened really fast. Since upgrading to 0.6.4 it takes abou 3 seconds to open 
it. Uninstalling 0.6.4 and reinstalling 0.6.3 solves the problem. Notebook 
opens in 1 sec or faster. Just to let you know.

What version of the product are you using? On what operating system?
0.6.4 on Windows 7/64 Ultimate DE; DELL Precision 490 with 2 x Dual Core Xeon 
5130 and 8GB RAM

Please provide any additional information below.


```

Original issue reported on code.google.com by `n...@bomhard.de` on 14 Sep 2010 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
Does the 0.6.5 speed up file loading.  You can also try the testing version 
0.6.6:
http://rasm.ods.org/keepnote/download-test/


```

Original comment by `matt.rasmus@gmail.com` on 17 Oct 2010 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
0.6.6 crashes on my xp/sp3

==============================================
KeepNote 0.6.6: Sun Oct 17 19:56:11 2010
enabling extension 'backup_tar'
enabling extension 'new_file'
enabling extension 'editor_insert_date'
enabling extension 'command_basics'
enabling extension 'export_html'
enabling extension 'python_prompt'
enabling extension 'keepnote'

Traceback (most recent call last):
  File "keepnote\gui\__init__.pyc", line 451, in open_notebook
  File "keepnote\notebook\__init__.pyc", line 1377, in load
  File "keepnote\notebook\__init__.pyc", line 1733, in read_preferences
  File "keepnote\safefile.pyc", line 86, in close
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "keepnote", line 399, in <module>
  File "keepnote", line 392, in main
  File "keepnote", line 265, in start_gui
  File "keepnote", line 335, in execute_command
  File "keepnote\gui\main_window.pyc", line 777, in open_notebook
  File "keepnote\gui\main_window.pyc", line 721, in _restore_windows
AttributeError: 'NoneType' object has no attribute 'pref'

```

Original comment by `epposan@gmail.com` on 18 Oct 2010 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
0.6.6 does indeed load a lot faster than 0.6.5
No crashing observed.
Debian Squeeze.

```

Original comment by `chk.6080...@gmail.com` on 18 Oct 2010 at 11:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 13 Nov 2010 at 8:22
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 9 Dec 2010 at 3:55
- Changed state: **Done**
