### ISSUE TITLE
crash due to mouse-scrolling ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#34]
```
Using Keepnote version 0.5.2, Ubuntu 8.10 AMD64. 

I don't know the precise cause, but I do know that I was scrolling with the
scroll-wheel a lot, and got the following traceback when the application
crashed:

==============================================
KeepNote 0.5.2: Tue Apr 14 15:34:47 2009
/usr/lib/python2.5/site-packages/keepnote/gui/main_window.py:1817:
DeprecationWarning: use gtk.UIManager
  self.accel_group)
/usr/lib/python2.5/site-packages/keepnote/gui/basetreeview.py:241:
GtkWarning: gtk_tree_model_sort_real_unref_node: assertion `VALID_ITER
(iter, tree_model_sort)' failed
  self.set_cursor(path2)

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/keepnote/gui/main_window.py", line
1381, in on_edit_image
    proc = subprocess.Popen([editor.prog, image_path])
  File "/usr/lib/python2.5/subprocess.py", line 594, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1153, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
/usr/lib/python2.5/site-packages/keepnote/gui/dialog_image_resize.py:55:
GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is
deprecated
  self.xml = gtk.glade.XML(get_resource("rc", "keepnote.glade"))

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/folder.png': No such
file or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/folder-open.png': No
such file or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/trash.png': No such file
or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/folder.png': No such
file or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/folder-open.png': No
such file or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/trash.png': No such file
or directory

(keepnote:376): libglade-WARNING **: could not convert string to type
`GdkPixbuf' for property `pixbuf'
/usr/lib/python2.5/site-packages/keepnote/gui/dialog_app_options.py:36:
GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is
deprecated
  "app_config_dialog")

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/keepnote/gui/main_window.py", line
1381, in on_edit_image
    proc = subprocess.Popen([editor.prog, image_path])
  File "/usr/lib/python2.5/subprocess.py", line 594, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1153, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

(inkscape:696): Gtk-WARNING **: GtkSpinButton: setting an adjustment with
non-zero page size is deprecated

(inkscape:696): Gtk-WARNING **: GtkSpinButton: setting an adjustment with
non-zero page size is deprecated

[this warning repeats another 30 times or so]
```

Original issue reported on code.google.com by `edgi...@gmail.com` on 14 Apr 2009 at 2:03

**Comment by GoogleCodeExporter** [comment]
```
Thanks for this feedback.

I think one issue that occurs here is that I have not install image icons 
correctly
in the resource folder.  That is what is causing this error:

(keepnote:376): libglade-WARNING **: Error loading image: Failed to open
file '/usr/lib/python2.5/site-packages/keepnote/rc/folder.png': No such
file or directory

The GtkSpinButton is only a deprecation warning coming from Inkscape (but that
shouldn't be a problem).

For this error:
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/keepnote/gui/main_window.py", line
1381, in on_edit_image
    proc = subprocess.Popen([editor.prog, image_path])
  File "/usr/lib/python2.5/subprocess.py", line 594, in __init__
    errread, errwrite)
  File "/usr/lib/python2.5/subprocess.py", line 1153, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


That means you did not set an image editor yet (See: Options > KeepNote Options 
>
Help Applications).

Do you know what error did cause the crash?  Is there another error at the end 
of the
error log?

```

Original comment by `matt.rasmus@gmail.com` on 14 Apr 2009 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
I did set the image editor, which maybe is what the problem was -- I set it to
/usr/bin/inkscape.  And it does run, and load the png.  But perhaps somehow this
caused keepnote to crash?

Originally what I was hoping to do was to insert a blank "SVG image" into a 
note, and
then when editing the image via keepnote's image menu, inkscape would edit the 
SVG
file, but this is currently not possible since the svg file is always converted 
to a
png first.  It would be nice if it would be copied as an SVG file into the 
keepnote
dirtree, and converted to pixbuf data on-the-fly.  Of course it would be nicest 
if it
were possible to create new drawing areas which could be directly edited 
without the
need to load inkscape (see issue #32) - but optionally being able to open the 
area
with an external tool.
```

Original comment by `edgi...@gmail.com` on 14 Apr 2009 at 3:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 8 Jul 2009 at 12:38
- Changed state: **Done**
