### ISSUE TITLE
Custom icons not available WinXP Pro SP3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#478]
```
What steps will reproduce the problem?
1. Right click on Tree node
2. Select Change icon from menu
3. Then select More Icons from sub menu

What is the expected output? What do you see instead?
I believe I should expect to see the New Icon / Manage Icons dialog (?) as 
pictured in manual 
http://keepnote.org/keepnote/manual.shtml#icons
http://keepnote.org/keepnote/images/screenshot-new-icon.png

Instead, nothing at all happens

What version of the product are you using? On what operating system?
KeepNote 0.7.2
Windows XP Professional SP3

Please provide any additional information below.

Error Log shows:

Traceback (most recent call last):
  File "keepnote\gui\three_pane_viewer.pyc", line 865, in <lambda>
  File "C:\Program Files\Accessories\KeepNote\extensions\python_prompt\__init__.pyc", line 699, in on_new_icon

  File "keepnote\gui\dialog_node_icon.pyc", line 146, in show
  File "keepnote\gui\dialog_node_icon.pyc", line 215, in populate_iconview
  File "keepnote\gui\dialog_node_icon.pyc", line 198, in populate_iconlist
NameError: global name 'GError' is not defined

```

Original issue reported on code.google.com by `bmadti...@gmail.com` on 1 Jun 2011 at 11:11

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this bug.  I have made a new testing version (0.7.4) that 
should address this issue:
http://keepnote.org/keepnote/#download-test

Please try it out and let me know if it works.

```

Original comment by `matt.rasmus@gmail.com` on 21 Jun 2011 at 2:40
