### ISSUE TITLE
Cannot Paste Keepnote text into Google App Sites on Firefox 3.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#78]
```
What steps will reproduce the problem?
1. Copy text in Keepnote
2. With firefox open google apps and click on sites. Open any site page.
3. Click edit
4. Paste text (All paste functions are not working)

What is the expected output? What do you see instead?
Text should paste as other application like gedit do

What version of the product are you using? On what operating system?
Keepnote: 0.5.2
OS: Ubuntu 9.04
Browser: Firefox 3.5

Please provide any additional information below.
I assume that it is because of all the Ajax stuff in the google app??

BTW. Excellent application.  I have been looking for exactly this for so long.

```

Original issue reported on code.google.com by `tomgo...@gmail.com` on 9 Jul 2009 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
Same problem in Ubuntu 8.04, KeepNote 0.6pre and Firefox 3.0.11
Can't copy a text from KeepNote to Gmail
```

Original comment by `thibaut....@gmail.com` on 24 Aug 2009 at 7:42

**Comment by GoogleCodeExporter** [comment]
```
interestingly drad'n dropping a bloc of text from KeepNote to Gmail works 
except for
accented characters
i.e "plutôt que êtes vous sûr" is turned into "plut\u00f4t que \u00eates 
vous s\u00fbr"
```

Original comment by `thibaut....@gmail.com` on 25 Aug 2009 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
Issue 85 has been merged into this issue.
```

Original comment by `matt.rasmus@gmail.com` on 1 Sep 2009 at 4:12

**Comment by GoogleCodeExporter** [comment]
```
Issue 169 has been merged into this issue.
```

Original comment by `matt.rasmus@gmail.com` on 7 Feb 2010 at 2:53

**Comment by GoogleCodeExporter** [comment]
```
Issue 188 has been merged into this issue.
```

Original comment by `matt.rasmus@gmail.com` on 7 Feb 2010 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
anything new concerning this bug ?
```

Original comment by `thibaut....@gmail.com` on 14 Apr 2010 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
I have made progress on this bug.  My HTML parsing was too strict.  You can try 
the
latest testing version (keepnote 0.6.3) to see if pasting works better.

http://rasm.ods.org/keepnote/download-test


```

Original comment by `matt.rasmus@gmail.com` on 1 May 2010 at 8:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 1 May 2010 at 8:32
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
i don't know if it's related but the latest testing version (keepnote 0.6.3) 
didn't
help for my copy/paste bug : if i 1°) copy a text from keepnote 2°) close 
Keepnote et
3°) try to paste the text, then nothing happens
```

Original comment by `thibaut....@gmail.com` on 2 May 2010 at 11:29

**Comment by GoogleCodeExporter** [comment]
```
in the other hand, the test case i mentioned in comment 2 now works
```

Original comment by `thibaut....@gmail.com` on 2 May 2010 at 11:31

**Comment by GoogleCodeExporter** [comment]
```
maybe that report can help https://bugs.launchpad.net/ubuntu/+bug/11334
```

Original comment by `thibaut....@gmail.com` on 16 May 2010 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
here is a summary of current state of the art
https://bugs.launchpad.net/ubuntu/+bug/11334/comments/216
```

Original comment by `thibaut....@gmail.com` on 24 May 2010 at 4:02

**Comment by GoogleCodeExporter** [comment]
```
from the spec :
"Responsibilities of clipboard owners
If a client needs to exit while owning the CLIPBOARD selection, it should 
request the
clipboard manager to take over the ownership of the clipboard, using the 
SAVE_TARGETS
mechanism. If there is no clipboard manager, or if the SAVE_TARGETS conversion 
fails,
the application should simply exit"
```

Original comment by `thibaut....@gmail.com` on 25 May 2010 at 7:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Jun 2010 at 6:13
- Added labels: **copypaste**

**Comment by GoogleCodeExporter** [comment]
```
I had this issue today : I wanted to copy and paste some text I typed in 
Keepnote into an email (Thunderbird) but the paste never worked :-( 
I had to too select "Paste without formatting" to get my text into my 
email...but I was quite sad to have lost my text formatting.
```

Original comment by `laurent....@gmail.com` on 15 Mar 2011 at 9:17

**Comment by GoogleCodeExporter** [comment]
```
Very good tool indeed with screenshots and everything in one place.
But having problems with Copy-Paste for FF 4.0.1 apparently something to do 
with UTF8 encoding

=============================================
KeepNote 0.7.2: Tue May 17 20:03:33 2011
enabling extension 'backup_tar'
enabling extension 'new_file'
enabling extension 'editor_insert_date'
enabling extension 'command_basics'
enabling extension 'export_html'
enabling extension 'python_prompt'
enabling extension 'keepnote'

Traceback (most recent call last):
  File "keepnote\notebook\connection\fs\__init__.pyc", line 864, in _read_node
  File "keepnote\notebook\connection\fs\__init__.pyc", line 283, in mark_path_outdated
WindowsError: [Error 5] Access is denied: u'C:\\Program 
Files\\KeepNote\\MyNoteBook\\brb 05-16-2011\\br4411095\\br4394551'
C:\Program 
Files\KeepNote\library.zip\keepnote\gui\richtext\textbuffer_tools.py:323: 
GtkWarning: gtk_text_buffer_emit_insert: assertion `g_utf8_validate (text, len, 
NULL)' failed

```

Original comment by `pil...@gmail.com` on 18 May 2011 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
I made some updates to copy and paste so that it works from more applications.  
Can some try it out and let me know if it works better now?
http://keepnote.org/#download-test

If you still have problems please to the following to help me debug.  Go to 
"Help > Drag and Drop Test".  A dialog box will appear with two text boxes.  
Perform a paste into the lower text box.  Debug information will appear which 
you can send to me.  Thanks.
```

Original comment by `matt.rasmus@gmail.com` on 2 Sep 2011 at 1:49

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 15 Sep 2011 at 2:26
- Changed state: **Done**
