### ISSUE TITLE
Cannot run under Windows XP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#95]
```
I download Windows version 0.53.
Install.
Run.
See small window: "Error - see log-file".

Log-file (keepnote.exe.log):

"Traceback (most recent call last):
  File "keepnote", line 261, in <module>
  File "keepnote", line 229, in main
  File "keepnote\__init__.pyc", line 226, in get_user_pref_dir
  File "ntpath.pyc", line 102, in join
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 26-27:
invalid data"

OS: Windows XP SP3 Pro Rus
```

Original issue reported on code.google.com by `inf.s...@gmail.com` on 4 Aug 2009 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
It looks like you have a character encoding issue on your file system.  What is 
the
path to your User directory and Application Data directory.  On my Windows 
computer
the application data directory is (in English locale): 

"C:\Documents and Settings\USER_NAME\Application Data"

Let me know what your equivalent is.  It will help me debug this issue.

Thanks,
Matt
```

Original comment by `matt.rasmus@gmail.com` on 5 Aug 2009 at 1:26

**Comment by GoogleCodeExporter** [comment]
```
Russian locale, Windows-1251

"c:\Documents and Settings\Ник\Application Data\"
```

Original comment by `inf.s...@gmail.com` on 5 Aug 2009 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Can you test the new version of KeepNote (version 0.6)?  Available for download 
from
here:
http://rasm.ods.org/keepnote/download-test/

I think it might address this issue.  Let me know if it works.
```

Original comment by `matt.rasmus@gmail.com` on 25 Aug 2009 at 3:16
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Yes, it is launch OK :)

Thank You
```

Original comment by `inf.s...@gmail.com` on 25 Aug 2009 at 6:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.rasmus@gmail.com` on 25 Aug 2009 at 2:58
- Changed state: **Fixed**
